# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QS41-TDJNJ3EOgX8FDt1x_Gob9cUyNgF
"""

import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns


import os
for dirname, _, filenames in os.walk('/content/notebooke3da6c750c_Kaggle1.html'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df=pd.read_csv("/content/NORMAL_DLY_sample_csv.csv")

df.shape

df.head()

df.describe()

df.info()

df.isnull().sum()

fig, axes=plt.subplots(figsize=(8, 6))
sns.heatmap(df.corr(), ax=axes)

from sklearn.model_selection import train_test_split
features=["precipitation", "temp_max", "temp_min", "wind"]
X=df[features]
y=df.weather
train_X, test_X, train_y, test_y = train_test_split(X, y,random_state = 0)

from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error

model1=DecisionTreeRegressor(random_state=1)
model1.fit(train_X, train_y)
pred1=model1.predict(test_X)
print("Mean Absolute Error: %f" %(mean_absolute_error(test_y, pred1)))

from sklearn.ensemble import RandomForestRegressor

model2=RandomForestRegressor(random_state=1)
model2.fit(train_X, train_y)
pred2=model2.predict(test_X)
print("Mean Absolute Error: %f" %(mean_absolute_error(test_y, pred2)))